- name: Deploy Docker container to EC2
  hosts: web
  become: yes

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull Docker image from Docker Hub
      docker_image:
        name: liamachihon/hello-liam
        source: pull

    - name: Run Docker container
      docker_container:
        name: hello-liam
        image: liamachihon/hello-liam
        state: started
        restart_policy: always
        ports:
          - "80:3000"
