- name: Deploy Docker Container
  hosts: all
  become: true
  vars:
    docker_image: liamachihon/hello-liam:latest
  tasks:
    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"

    - name: Run Docker container
      community.docker.docker_container:
        name: hello-liam
        image: "{{ docker_image }}"
        ports:
          - "80:3000"
        state: started
        restart_policy: always
